CREATE TABLE category (
id INT NOT NULL AUTO_INCREMENT,  
category_name VARCHAR(200) NOT NULL, 
PRIMARY KEY (id)
);

CREATE TABLE qualification (
id INT NOT NULL AUTO_INCREMENT,
category_name INT NOT NULL,
code VARCHAR(300) NOT NULL,
name VARCHAR(300) NOT NULL,
description VARCHAR(300) NOT NULL,
job_rules VARCHAR(300) NOT NULL,
fees VARCHAR(300) NOT NULL,
packaging_rules VARCHAR(300) NOT NULL,
PRIMARY KEY (id),
FOREIGN KEY (category_name)
	REFERENCES category(id)
	ON DELETE CASCADE

);

CREATE TABLE contact (
id INT NOT NULL AUTO_INCREMENT,
name VARCHAR(300) NOT NULL,
email VARCHAR(300) NOT NULL,
phone_number BIGINT NOT NULL,
message VARCHAR(300) NOT NULL,
PRIMARY KEY (id)
);

CREATE TABLE testimonials (
id INT NOT NULL AUTO_INCREMENT,
image LONGBLOB NOT NULL,
name VARCHAR(100) NOT NULL,
designation VARCHAR(200) NOT NULL,
message VARCHAR(300) NOT NULL,
PRIMARY KEY (id)
);